### ISSUE TITLE
Invalid Management Message Response

### ISSUE THREAD

**Issue by hhhansen** [ptpd/ptpd#14]
I've recognized that Management Responses are not correct. Please have a look into the attached Wireshark capture. Packet 15 shows the wrong CONTROL (sync instead of management) information.

[Invalid Management Messages.zip](https://github.com/ptpd/ptpd/files/136212/Invalid.Management.Messages.zip)

**Comment by wowczarek** [comment]
Hans,

You are correct. It is accidentally set to 0x00 instead of 0x04, we'll fix this.

However, as a side note - the use of controlField is deprecated in PTPv2, it is only there for backwards compatibility with V1. MessageType is the field to use in v2.

Thanks,
Wojciech

**Comment by hhhansen** [comment]
Wojciech,

ok, thank you!

Hans

**Comment by wowczarek** [comment]
Fix committed.
