### ISSUE TITLE
One Way Delay, Slave to Master --> 0.000000000 when using ptpd as Slave

### ISSUE THREAD

**Issue by schoerg** [ptpd/ptpd#15]
I am using ptpd in slave mode. This is the version that I'm using, it is not the newest one, but this one was available from package sources.
`  ptpd -g -b eth0 -D -f /var/log/ptpd/stats.log`

`  Installed: 2.2.2-debian1-2`
 `   Candidate: 2.2.2-debian1-2`
`    Version table:`
`   *** 2.2.2-debian1-2 0`
`          500 http://ba.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages`
`          100 /var/lib/dpkg/status`

My master clock is running ptp4l with (hopefully?) hardware timestamping.
`  ptp4l -4 -H -i p1p1`

The associated network card doing this is an Intel 82574L.

ethtool output:

```
Time stamping parameters for p1p1:
Capabilities:
	hardware-transmit     (SOF_TIMESTAMPING_TX_HARDWARE)
	software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
	hardware-receive      (SOF_TIMESTAMPING_RX_HARDWARE)
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
	hardware-raw-clock    (SOF_TIMESTAMPING_RAW_HARDWARE)
PTP Hardware Clock: 0
Hardware Transmit Timestamp Modes:
	off                   (HWTSTAMP_TX_OFF)
	on                    (HWTSTAMP_TX_ON)
Hardware Receive Filter Modes:
	none                  (HWTSTAMP_FILTER_NONE)
	all                   (HWTSTAMP_FILTER_ALL)
	ptpv1-l4-sync         (HWTSTAMP_FILTER_PTP_V1_L4_SYNC)
	ptpv1-l4-delay-req    (HWTSTAMP_FILTER_PTP_V1_L4_DELAY_REQ)
	ptpv2-l4-sync         (HWTSTAMP_FILTER_PTP_V2_L4_SYNC)
	ptpv2-l4-delay-req    (HWTSTAMP_FILTER_PTP_V2_L4_DELAY_REQ)
	ptpv2-l2-sync         (HWTSTAMP_FILTER_PTP_V2_L2_SYNC)
	ptpv2-l2-delay-req    (HWTSTAMP_FILTER_PTP_V2_L2_DELAY_REQ)
	ptpv2-event           (HWTSTAMP_FILTER_PTP_V2_EVENT)
	ptpv2-sync            (HWTSTAMP_FILTER_PTP_V2_SYNC)
	ptpv2-delay-req       (HWTSTAMP_FILTER_PTP_V2_DELAY_REQ)

```

Now to the issue.

If I look in the slave log, I see lines like this:

```
2016-02-22 09:11:24.258947, slv, 6805cafffe39dabc(unknown)/01,  0.000000000,  0.000000365,  0.000000000,  0.000001337, 31081, 0, S
2016-02-22 09:11:25.259040, slv, 6805cafffe39dabc(unknown)/01,  0.000000000,  0.000002293,  0.000000000,  0.000003250, 31083, 0, S
2016-02-22 09:11:26.259097, slv, 6805cafffe39dabc(unknown)/01,  0.000000000,  0.000002104,  0.000000000,  0.000000958, 31085, 0, S
2016-02-22 09:11:27.259169, slv, 6805cafffe39dabc(unknown)/01,  0.000000000,  0.000000642,  0.000000000,  0.000000327, 31085, 0, S

```

One Way Delay and Slave to Master are 0, my feeling says that this can not be correct, as the one-way-delay should at least be larger than 0.
This slave has a Broadcom BCM5754 NIC.

```
Time stamping parameters for eth1:
Capabilities:
	software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
PTP Hardware Clock: none
Hardware Transmit Timestamp Modes:
	off                   (HWTSTAMP_TX_OFF)
	on                    (HWTSTAMP_TX_ON)
Hardware Receive Filter Modes:
	none                  (HWTSTAMP_FILTER_NONE)
	ptpv1-l4-event        (HWTSTAMP_FILTER_PTP_V1_L4_EVENT)
	ptpv2-l4-event        (HWTSTAMP_FILTER_PTP_V2_L4_EVENT)
	ptpv2-l2-event        (HWTSTAMP_FILTER_PTP_V2_L2_EVENT)

```

I also have another slave, same output in the logfile:

```
2016-02-22 09:13:36.265614, slv, 6805cafffe39dabc(unknown)/01,  0.000000000,  0.000021380,  0.000000000,  0.000030137, -3721, 0, S
2016-02-22 09:13:37.265580, slv, 6805cafffe39dabc(unknown)/01,  0.000000000,  0.000001287,  0.000000000, -0.000027563, -3720, 0, S
2016-02-22 09:13:38.265691, slv, 6805cafffe39dabc(unknown)/01,  0.000000000, -0.000005543,  0.000000000,  0.000016477, -3725, 0, S
```

The drift here is way better than the other slave, probably because the NIC (Intel 82579LM) on this machine has some hardware timestamping function. But I thought they are not active in ptpd, or is the NIC doing some stuff here?

```
Time stamping parameters for eth1:
Capabilities:
	hardware-transmit     (SOF_TIMESTAMPING_TX_HARDWARE)
	software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
	hardware-receive      (SOF_TIMESTAMPING_RX_HARDWARE)
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
	hardware-raw-clock    (SOF_TIMESTAMPING_RAW_HARDWARE)
PTP Hardware Clock: 0
Hardware Transmit Timestamp Modes:
	off                   (HWTSTAMP_TX_OFF)
	on                    (HWTSTAMP_TX_ON)
Hardware Receive Filter Modes:
	none                  (HWTSTAMP_FILTER_NONE)
	all                   (HWTSTAMP_FILTER_ALL)
	ptpv1-l4-sync         (HWTSTAMP_FILTER_PTP_V1_L4_SYNC)
	ptpv1-l4-delay-req    (HWTSTAMP_FILTER_PTP_V1_L4_DELAY_REQ)
	ptpv2-l4-sync         (HWTSTAMP_FILTER_PTP_V2_L4_SYNC)
	ptpv2-l4-delay-req    (HWTSTAMP_FILTER_PTP_V2_L4_DELAY_REQ)
	ptpv2-l2-sync         (HWTSTAMP_FILTER_PTP_V2_L2_SYNC)
	ptpv2-l2-delay-req    (HWTSTAMP_FILTER_PTP_V2_L2_DELAY_REQ)
	ptpv2-event           (HWTSTAMP_FILTER_PTP_V2_EVENT)
	ptpv2-sync            (HWTSTAMP_FILTER_PTP_V2_SYNC)
	ptpv2-delay-req       (HWTSTAMP_FILTER_PTP_V2_DELAY_REQ)

```

Is this behaviour correct?

Thank you.

**Comment by wowczarek** [comment]
Hi,

1. PTPd 2.2.2 from Debian is an old, unsupported version. You should try the latest 2.3.1.
2. The log is non-conclusive: either PTPd is not sending Delay Request or ptp4l is not responding to it.
3. This could be a network issue - do you see the Delay Request arriving at the master? Are you sure it is leaving the ptpd host via the right interface?

Thanks,
Wojciech

**Comment by schoerg** [comment]
Thank you for your response.

I have made captures which hopefully can help you. One with ptpd 2.2.2, and another one with ptpd 2.3.1.
With 2.2.2 I didn't see Delay Responses, which might hint that ptp4l is not sending those out, but with 2.3.1 those delay responses are there.
The hosts are connected via a Hub, the clients only have one interface.

With 2.3.1 however, there seems to be an offset in the set time. The offset is about 36 seconds, which I assume are leap seconds. But this could also be originating from the master running ptp4l.

[ptpd.tar.gz](https://github.com/ptpd/ptpd/files/144648/ptpd.tar.gz)

**Comment by wowczarek** [comment]
There were large numbers of bugs fixed between 2.2 and 2.3.

The 36-second offset is indeed a problem with leap seconds. Unless the master is running in TAI timescale, which I don't think it is, you should set it to ARB timescale and not set leap seconds.

The problem is most probably that the master is already running in UTC time, so configuring it to send leap seconds causes "double leap seconds correction". 

You did not have this problem with 2.2.2 because by default, PTPd was ignoring leap seconds if the PTP_UTC_REASONABLE / currentUtcOffsetValid in your master's announce is FALSE, which is the case here. This was changed in 2.3 and by default, leap seconds field is always honoured, regardless of the valid flag, because it is a valid condition.

There are two options for you here:
1. Verify what the native time scale of the master is - if it's UTC, then you don't need to set the leap seconds value on the master
2. In ptpd, set ```ptpengine:always_respect_utc_offset=N```

Thanks,
Wojciech

**Comment by wowczarek** [comment]
To verify the leap seconds issue, check the timestamps sent in the Sync / FollowUp by the master. If these timestamps match UTC, there is no need to set the leap seconds value.

PTP defines two timescales:

1. PTP timescale, where all timestamps are in TAI time (no leap second correction), and TAI-to-UTC offset is sent in the Announce messages
2. Arbitrary timescale (ARB), where leap seconds are not used and timestamps are used as-is

This is fine for hardware GMs that take time from GPS - they always use PTP timescale and send TAI time.

PTPd in master mode assumes that the internal clock is running UTC, so it converts it to TAI and then sends out TAI and leap seconds value.

Judging by what you are getting from the ptp4l master, it may be the case that it is sending all timestamps already in UTC, but by sending out leap seconds information it makes the slave assume that they are TAI, hence the double correction.

**Comment by schoerg** [comment]
ptp4l is sending out time in UTC. I checked the preciseOriginTimestamp in the FollowUp message, as the Sync message did not have a originTimestamp value set. (It was set to 0)

**Comment by wowczarek** [comment]
That's fine in two-step, only FollowUp needs the timestamp.

OK, so you have the two options I mentioned two comments above.
