### ISSUE TITLE
Ignore lock file option causing sync and messaging problems

### ISSUE THREAD

**Issue by dougcooper** [ptpd/ptpd#17]
I have a use case where a single machine runs multiple daemons in parallel where each is bound to separate interface. One daemon runs as a slave while the others run as masters. The idea here is that the slave daemon sets the local time while the master daemons synchronize with computers connected to the associated interface. There are two distinct issues I've encountered in configuring the daemons:

1. When a daemon is in slave only mode and told to ignore lock files, it does not synchronize with the grand master, nor does it respond to management messages. The .status file shows that the daemon stays in a listening mode with no RX packets received. When using the default locking mechanism (no option passed), it works as expected - it enters slave mode and responds to management messages.
2. When the daemon is in masterslave mode and passed the argument to ignore lock files, it does not respond to management messages, but does synchronize properly with a slave located on another machine. When using the default locking mechanism (no option passed), it works as expected - it responds to management messages.

- I have tested the above with both short and long versions of the flags as well as passing a configuration file. 

- I have used both a hard and soft grand master - no change.

- I am running CentOS 6.6

**Comment by dougcooper** [comment]
Hi Wojciech,

Thanks for the quick response yesterday. I had a chance to test the reverted code this morning and it works as expected. I can now run all instances while ignoring lock files and they run/communicate as expected.

With regards to the referenced issue, the title of the patch seems to conflict with the description. Is the use case attempting to bind a single daemon to multiple interfaces?

-Doug

**Comment by wowczarek** [comment]
Doug,

The patch was specific to FreeBSD. No, the patch intends to build each deamon to a single interface only. This makes difference to Unicast, but on Linux prevents multicast from working correctly.

We're going to fix this for all platforms at some point anyway.

Thanks,
Wojciech
