### ISSUE TITLE
ptpd in slaveonly mode stops running after some hours

### ISSUE THREAD

**Issue by chris-jo** [ptpd/ptpd#22]
I want to synchronize a slave cpu to a master cpu. The ptpd in masteronly mode runs perfectly. But I have problems with the ptpd in slaveonly mode. After some hours it is dead and I have to kill it (kill -8) an restart it.

Version: ptpd v2.3.1
Hardware: IMX6

This is how I startet ptpd:

```
# strace -o strace.log /usr/bin/ptpd2 --config-file /etc/ptpd.conf -C
Warning: It is recommended to set the delay request interval (ptpengine:log_dela
yreq_interval) in unicast mode
2016-06-16 06:04:36.195419 ptpd2[438].startup (info)      (___) Configuration OK
2016-06-16 06:04:36.209302 ptpd2[438].startup (info)      (___) Successfully acquired lock on /var/run/ptpd2.lock
2016-06-16 06:04:36.218048 ptpd2[438].startup (notice)    (___) PTPDv2 started successfully on eth0.2 using "slaveonly" preset (PID 438)
2016-06-16 06:04:36.219717 ptpd2[438].startup (info)      (___) TimingService.PTP0: PTP service init
```

I use unicast mode but I also had the same problem in multicast mode.
The logs of the ptpd are attached and I also added my pdpd.conf and a shortend strace log.

I can't recognize any error, but maybe someone else could help me. I also can provide more information if needed.

[ptp-strace-short.log.txt](https://github.com/ptpd/ptpd/files/318512/ptp-strace-short.log.txt)
[ptpd.conf.txt](https://github.com/ptpd/ptpd/files/318513/ptpd.conf.txt)
[ptpd2.event.log.txt](https://github.com/ptpd/ptpd/files/318514/ptpd2.event.log.txt)
[ptpd2.stats.log.txt](https://github.com/ptpd/ptpd/files/318510/ptpd2.stats.log.txt)
[ptpd2.status.log.txt](https://github.com/ptpd/ptpd/files/318511/ptpd2.status.log.txt)

Thanks Chris

**Comment by wowczarek** [comment]
Hi,

If you are using the official 2.3.1 from sourceforge, you could have been affected by a bug where a timer accidentally gets armed for 0 duration and the process sits at an infinite alarm processing loop. Try using the current source from github.

**Comment by chris-jo** [comment]
OK, I tested the current source from github for more than 24h now and I had no problems.
Therefore, I think the problem is solved.
Thank you for you effort.
Is 2.3.2 already a stable version?

**Comment by diamondman** [comment]
@chris-jo looks like this should be closed.
