### ISSUE TITLE
Removing type U64 from net-snmp related code

### ISSUE THREAD

**Issue by j123b567** [ptpd/ptpd#25]
net-snmp package will remove U64 in next release, because it is conflicting with new perl. https://sourceforge.net/p/net-snmp/code/ci/477b4307ef12ddce3b6a9205e0bdddbfb2e0e9b6/

Related gentoo bug https://bugs.gentoo.org/show_bug.cgi?id=587328

ptpd should use `struct counter64` instead of `U64` in `snmp.c` for backward and forward compatibility.

**Comment by wowczarek** [comment]
Merged Jan's fix.
