### ISSUE TITLE
originTimestamp is zero

### ISSUE THREAD

**Issue by jllorente** [ptpd/ptpd#29]
Hi,

I'm trying to setup a Ubuntu server that synchronizes its time via NTP and sends PTPv2 downstream via unicast messages. In my current setup I'm using unicast negotiation.
The problem that I'm facing is that after the host sends a "Signalling message" with the requested rate to the server, the server answers with another "Signalling message" granting the requests and then following a number of "Announce message" with originTimestamp (both seconds and nanoseconds) set to zero. My host does not seem to like it and fails to synchronize and request unicast transmission in another "Signalling message".  However, I have noticed that the current clock we have running in the network actually sends the originTimestamp with some initial values... 

Thanks!
Jesus

**Comment by wowczarek** [comment]
Hi Jesus,

**13.5.2.1 originTimestamp (Timestamp)**
_The value of originTimestamp shall be **0 or an estimate** no worse than ±1 s of the local time of the
originating clock when the Announce message was transmitted._

In this  case I would say PTPd is still compliant, but your slave device is not, because it is expecting a timestamp in Announce. Even if we do embed a timestamp in the Announce message, which we can do, it is not expected to be precise. This is quite to fix on our end. Is your slave a hardware device?

**Comment by jllorente** [comment]
Hi, thanks for getting back to me so quickly!
It seems this hardware device expects to get the current time already in the Announce message before it requests the unicast transmission with a rate of 16 messages per second.

I'm not very familiar with the code, so do you think it would be possible to test this modification?

Best,
Jesus

**Comment by wowczarek** [comment]
Just committed the fix - please refresh your source and test. It is not guaranteed to fix your slave (this could be another issue), but the OriginTimestamp in Announce is no longer 0.

**Comment by jllorente** [comment]
Thanks a lot! I will test it ASAP and get back to you :)

**Comment by jllorente** [comment]
Hi! I had to use "./configure --disable-statistics" for building the new version, the normal "./configure" would otherwise fail to compile... Now my slave was able to synchronize, but after some time it kind of drifts away and the synchronization is lost due a difference in its reference signal and the master clock.
I tried to make my master sync its time to NTP but I don't think I have configured it properly. Do you have any hints about how could I go about this?
Thanks!

**Comment by wowczarek** [comment]
Hi - what failed in the configure script?

**Comment by jllorente** [comment]
So, if I  `./configure --enable-debug-level=all` then I get some compilation errors:
signaling.c:331:55: error: ‘tmpAddr’ undeclared (first use in this function)
signaling.c:464:55: error: ‘tmpAddr’ undeclared (first use in this function)
signaling.c:557:55: error: ‘tmpAddr’ undeclared (first use in this function)

**Comment by wowczarek** [comment]
Hi - I committed a fix for this, but really the enable-debug-level is an old option that will be removed at some point, it's just --enable-runtime-debug and multiple -D -D -D when you run it. Also do not configure with --disable-statistics. This removes a lot of functionality but is there only to provide an option for a very light build with no heavy math computations (for microcontrollers etc).

**Comment by wowczarek** [comment]
I will leave the NTP part for you to figure out... PTPd only servers whatever system time it has.

**Comment by wowczarek** [comment]
Closing issue as the original problem was resolved.
