### ISSUE TITLE
Missing definition of MANUFACTURER_ID in 'src/constants.h'

### ISSUE THREAD

**Issue by da-phil** [ptpd/ptpd#3]
MANUFACTURER_ID is not defined and gets printed out in ```src/protocol.c```, but only if ```RUNTIME_DEBUG``` is set, that might be the reason why nobody encountered a build error lately.
It should be assigned a default value in ```src/constants.h```.

**Comment by wowczarek** [comment]
Hi - yes, this was identified already, I just need to push some of my last changes.

**Comment by wowczarek** [comment]
Pushed in the last commit.
