### ISSUE TITLE
PTPv1 and PTPv2 included in PTPd?

### ISSUE THREAD

**Issue by PTPluckybee** [ptpd/ptpd#41]
Hello
 I have a project that requires both versions of PTP, version 1 and version 2.
Does PTPd support both?
Thank you.
Bernard.

**Comment by PTPluckybee** [comment]
Hi,
I see that, at some point, Feb 2014 I think, legacy PTPv1 multicast group support was removed. https://github.com/ptpd/ptpd/commit/b82172b7c548994af3a6958a0ea2d899012c9bdb
Does that mean that earlier version supported PTPv1?
Thank you.
Bernard.

**Comment by gvnn3** [comment]
The current code base does not support PTPv1.  V1 support was deprecated several years ago.
