### ISSUE TITLE
ptpd for android

### ISSUE THREAD

**Issue by niliqiang** [ptpd/ptpd#58]
Hello,

I want to syncronize Android devices via PTP.
Is it possible to port ptpd to an Android device?? Or there is a plan for it? I‘m a beginner on PTP.
And I want to know which project is recommended for porting? ptpd or [linuxptp](https://github.com/richardcochran/linuxptp)?

Thank you very much!

**Comment by j123b567** [comment]
Android uses Linux kernel so maybe no need to port anything. Just try it, both can work.

**Comment by wation** [comment]
Could you show me the Makefile for Android?

**Comment by niliqiang** [comment]
> Android uses Linux kernel so maybe no need to port anything. Just try it, both can work.

Thanks for your reply! 
I don't konw how to run linux application on android devices, so I finally realized the time synchronization of the android device by receiving and sending the PTP messages.

**Comment by niliqiang** [comment]
> Could you show me the Makefile for Android?
Sorry, I may not help you.
I don't konw how to run linux application on android devices. If you know, plz let me know, thanks! I finally developed an Android app to receive the PTP master clock messages, thus realizing the time synchronization of the Android device.

**Comment by niliqiang** [comment]
> Could you show me the Makefile for Android?

Sorry, I may not help you.
I don't konw how to run linux application on android devices. If you know, plz let me know, thanks! I finally developed an Android app to receive the PTP master clock messages, thus realizing the time synchronization of the Android device.

**Comment by wowczarek** [comment]
https://github.com/wowczarek/ptpd/tree/wowczarek-2.3.2-libcck builds cleanly on Android / llvm (Termux). However some syscall definitions are missing like `adjtimex()` and `clock_adjtime` which are sort of crucial, but that may be down to libandroid/bionic. Test system is not rooted anyway. Manually adding syscall numbers may work.

**Comment by benv2k6** [comment]
You can build it with musl (https://musl.cc/). Creating statically compiled binary to run on aarch64 (without using the ndk)
```
LDFLAGS="-static -static-pie -static-libgcc -Wl,-static" CFLAGS="-static" CC=$MUSL/bin/aarch64-linux-musl-gcc  ac_cv_func_malloc_0_nonnull=yes ./configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu && make -j
```
This one solved the dependecy of `bionic` since its using a regular  aarch64 tool-chain

So just use the release available from this repo (https://github.com/ptpd/ptpd/releases/tag/ptpd-2.3.1 for this point in time)
I've tested it on an android 10.0 device, with syncing to WSL (on windows) running ptp master.

**Comment by neuralRob** [comment]
Hi, I'm native to this topic but I got here by looking for a way to precisely synchronise my android smartphone and a laptop (possibly a Mac). Could you please give me some advice on which are the tools I would need to accomplish this?

**Comment by benv2k6** [comment]
Hi @neuralRob , you could reference my comment above. 
The steps are:
1. Build ptp client for Android 
2. Use ptp server on the mac
3. Use a config for both client and server as per ptp documentation for establishing the connection and syncing the time of the client by the server

It works well when using a dedicated router
And here is also a reference I've used:
https://jackhenderson.com.au/projects/time-synchronisation


Not that maybe you could use ntp instead if you dont need high precision,and there are Android apps that let you specify ntp server and sync Androids clock accordingly, so it this case you just need to run ntp server on your mac.

Note that both solutions require you to have root access to your phone.

**Comment by JzHuai0108** [comment]
Hi @benv2k6, I am working on a project that connect an external lidar to an android phone via a RJ45 to type-C connector. And we'd like to sync the lidar's time to the android by PTP.
Currently, the phone can communicate with the lidar by sending commands, and receiving lidar data.
The lidar supports the precise time protocal.
I think we need to run a PTP server on the android phone, and then sync the lidar.
Do you think this approach is workable?
I think the crux is about how to set up the PTP server on the phone without rooting it.

**Comment by benv2k6** [comment]
Hi, that sounds like a good approach given sudo privileges are not needed
for running the ptpd server (and for that I'm not sure, as for when we used
it, android was client and it the client ran as sudo)

בתאריך יום ב׳, 18 בנוב׳ 2024, 6:33, מאת JzHuai0108 ‏<
***@***.***>:

**Comment by JzHuai0108** [comment]
Thank you for the quick response. I think we will proceed to implement it. By the way,
a) I am thinking to write a small android app myself to publish SYNC and FOLLOW_UP messages which are those published by PTP master clock.
b) An alternative approach is to port the ptpd or the like onto android and then run the PTP server.
Which approach do you think is more reliable and requires less effort?

**Comment by JzHuai0108** [comment]
After further reading, I find the android doc about [network time detection](https://source.android.com/docs/core/connect/time/network-time-detection) very clarifying.
And I spotted a paper about [ptpd on android](https://ieeexplore.ieee.org/document/6229497).
According to their vague experiment description, it seems possible to run ptpd as a master clock on android phones.

**Comment by benv2k6** [comment]
Very interesting! Good luck 🤞

בתאריך יום ב׳, 18 בנוב׳ 2024, 13:24, מאת JzHuai0108 ‏<
***@***.***>:
