### ISSUE TITLE
PTP masters running on RHEL 5.4 send malformed follow up messages

### ISSUE THREAD

**Issue by eroglyph** [ptpd/ptpd#6]
Hello,
I've got a legacy Red Hat 5.4 i686 machine we want to run ptpd 2.3.1 on as a master clock. When I run the program ptpd starts up as a master as expected. However, on the slave end, all I see are Delay Response packets with all fields set to 0 like this

    2015-12-03 07:10:29.107100, slv, 525400fffe202102(unknown)/1, 0.000000000, 0.000000000, 0.000000000, 0.000000000, 11467.193603516, D, 0.000000000, 0, 0.000000000, 0, 0, 0, 0.000000000, 0.000000000

When I enable debug mode on the slave I see this error message

    (slv) ignord unicast message in multicast mode 2

This doesn't make any sense, since I'm running both master and slave in multicast mode. I've tried 5.4 x86_64 in an attempt to track down the issue and it still has the same behavior. I don't see this issue in RHEL 6, but upgrading would affect other legacy programs we have in the system.

**Comment by wowczarek** [comment]
Hi - try building current git source - we are approaching another release. Can you attach a capture of the traffic being sent by the master?

**Comment by eroglyph** [comment]
It looks like the latest source fixes the problem. Would that be v2.3.2? Thanks!

**Comment by wowczarek** [comment]
Hi - yes, this is the unreleased 2.3.2. This was a problem with the Unicast flag being incorrectly set.
