### ISSUE TITLE
Quorum of Grandmaster Clocks or Quorum of any PTPd clients-servers RE NTP-SEC Quorum Fix

### ISSUE THREAD

**Issue by aspadistra** [ptpd/ptpd#60]
Quorum of Grandmaster Clocks
or a 
Quorum of any PTPd clients-servers 

RE NTP-SEC Quorum Fix

NTP-org only recently fixed a long running "Security Issue" by requiring client-server sync to only be made final or doable if and only if there is a quorum of available NTP servers (LOCAL or GLOBAL). 

The way PTPd seems to depend on "one and only one" or at best local 2 Grandmasters is just begging for spoofing, local or global. 

There is NO DEFAULT CONFIG for most LINUX BRANCHES -- so it all just begs for trouble. 

As most PTP configs have NTP also running, this massive security and reliability problem has been hidden by over-provisioning. 

PTP should be able to run SOLO like NTP, and work with reasonably better reliability.

**Comment by j123b567** [comment]
Why should most PTP configs have also NTP? There is no need to use NTP. You can just run PTPd alone and it will work.

Please read the IEEE 1588-2008 specification or at least some wikipedia articles prior commenting, how PTP works and how PTPd is implemented. PTP in multicast mode should use one and only one master selected by distributed Best Master Clock Algorithm (BMCA) and this is how it SHOULD work. If the master is gone, then new master is selected by BMCA. Any node in principle can became new master so it is not limited to 2.
If you need to prevent spoofing, you should use PTP software, that implements security extension/authentication. I think PTPd does not have support for this authentication.
You can also use special network switches implementing PTP. They can limit which device can become master. They will also increase overall synchronization precision.

PTP is not replacement for NTP and is not designed for global internet. It targets completely different segment of specialized local networks with high synchronization precision in mind.

**Comment by aspadistra** [comment]
As most PCs and most modern Laptops have clocks and timers that can on average have a resolution of 10ms there is no reason why -- when running NTP + PTP -- that on megabit connections that one's OS clock can't be off by no more than 15ms to 25ms. 

Most LINUX and BSD builds (if they are maintained properly, and consider users needs) have NTP (but mostly not yet NTP-SEC) ... but PTP not at all. 

PTP in Hybrid Mode is more NTP like, and PTP does have some settings that allow it to interoperate (in non-HW timestamp modes) with NTP. 

It would be nice if ISP routers were configured to be PTP servers, as this is only a software modification. 

This would at least guarantee a forest of PTP servers that would always be available. 

PTP is too good -- in spite of its design flaws -- to just be used in TEST-CALIBRATION-TELECOM-SCIENTIFIC circles.

**Comment by j123b567** [comment]
You are talking about tens of milliseconds! This is area where you can happily live with NTP without problem. PTP is designed to achieve sub-microsecond accuracy. (With software timestamping and PTPd, you ca achieve tens of microseconds.)

ISP routers are completely out of the scope of this project so closing this as off-topic.
