### ISSUE TITLE
BMC Algorithm logic is backwards

### ISSUE THREAD

**Issue by bautolp** [ptpd/ptpd#63]
Line 769-772 of BMC states:
for (i=1,best = 0; i<ptpClock->number_foreign_records;i++)
		if ((bmcDataSetComparison(&foreignMaster[i], &foreignMaster[best],
					  ptpClock, rtOpts)) < 0)
			best = i;
Where the bmcDataSetComparison returns -1 for B better than A, meaning if best is better than i, it replaces best with i, which is the opposite of what it should do. This works for most cases because the statement below will deal with it. But when you have many daemons running on different devices on a network and they all enable at the same time, you can get a loop where oyu have several masters set incorrectly. I have solved an verified the fix of changing to > 0 on my devices.

**Comment by wowczarek** [comment]
...just that bmcDataSetComparison returns -1 for A better than B, not the other way round. In BMCA and in all these comparisons, lower == better.
