### ISSUE TITLE
Year 2038 problem and ptpd (802.1AS)

### ISSUE THREAD

**Issue by Benikz** [ptpd/ptpd#65]
I have come to a recent problem where I tested ptpd and it seems that integer32 are used for seconds, which leads to year 2038 problem...
I am referring to this: https://en.wikipedia.org/wiki/Year_2038_problem

Eventhough the types are defiend correctly (UInteger48), they are not used:
https://github.com/ptpd/ptpd/blob/master/src/ptp_primitives.h

Instead, TimeInternal defines signed integer32 as seconds:
typedef struct {
	Integer32 seconds;
	Integer32 nanoseconds;
} TimeInternal;
https://github.com/ptpd/ptpd/blob/master/src/ptp_datatypes.h

My suggestion would be:
1. Hotfix would be using unsigned integer32 to extend the time until year 2106.
2. Use the Uinteger48 (specified in 802.1AS spec) and adjust all algorithms.
3. Use Uinteger64 (not specified) for seconds

P.S.: Is this page still supported?

**Comment by evk1206** [comment]
Hello @Benikz  , May I ask why this issue is closed, is it already fixed ?
