### ISSUE TITLE
Why is there a need to re-arm timer for sending delay request?

### ISSUE THREAD

**Issue by qning88** [ptpd/ptpd#70]
Hi, this is not a bug. 

I'm in the process of modifying ptpd to include hardware timing from the FPGA. 

I would like to understand why is there a need to rearm the timer for sending Delay Request. 

In file "protocol.c" inside function "issueDelayReq", there is a comment that says:

"Explicitly re-arm timer for sending the next delay request.
9.5.11.2: arm the timer with a uniform range from 0 to 2 x interval." 

As a result of the above, I see delay request being sent one after another. 

Why don't we use a periodic timer for sending Delay Request for the PTP_SLAVE? A periodic timer is used to send SYNC message from the PTP_MASTER. 

Thanks for reading.

**Comment by wowczarek** [comment]
Hi there,

The comment you cited, refers to a specific clause in the IEEE standard. Delay request intervals are not exact but always random between subsequent (0) and twice the master's prescribed interval - with this being random with a normal distribution, the _average_ interval is "correct". This randomness is there to ensure uniform network load and prevent coinciding bursts of requests to the master. We arm, timer fires, and we arm again for the new random interval. A "side effect" is also the fact that the interval may be reconfigured on the master at any time and so if  a new value of logMessageInterval arrives in DelayResp, the slave automatically changes its request rate. I can't recall if Sync intervals also need to be randomised or not...

Edit: There is no explicit requirement to randomise Sync intervals (clause 9.5.9), so this answers your question why we re-arm the Delay_Req timer and not sync.

**Comment by qning88** [comment]
Thanks so much for the clear explanation!! 

In the 2.3.1 code that i have downloaded, I don't see a randomised Sync interval (I will check more thoroughly again just to make sure). If time permit, I will take into consideration when I mod the codes.
