### ISSUE TITLE
NTPd integration is broken

### ISSUE THREAD

**Issue by kirgene** [ptpd/ptpd#8]
I configured integration of PTPd with NTPd and when I start PTPd I'm getting following warning message:
```
TimingService.NTP0: Could not start NTP service. Will keep retrying.
```
After adding `enable mode7` in `ntp.conf` I managed to fix this issue.
Seems that PTPd uses deprecated NTP stuff (see [this](http://lists.ntp.org/pipermail/questions/2014-January/037149.html) thread).

**Comment by wowczarek** [comment]
So it's not broken then. Regarding mode 7 - we are aware. Mode 7 is now disabled by default but will do you no harm if running on localhost only. Older systems run versions of NTPd that do not support remote reconfiguration via mode 6 - for now, as long as mode 7 support is not actually removed, we are going to continue as is.  There are other items on the priority list, but eventually we are either going to use mode 6 or shm.

**Comment by kirgene** [comment]
I see, thanks for explanation.

**Comment by jllorente** [comment]
Hei @kirgene, were you able to configure ntpd and ptpd for proper interaction?

**Comment by wowczarek** [comment]
@jllorente This is only useful for using NTPd as a backup for PTPd running as slave. If your case is to run PTPd as master and system time comes from NTP, you don't need any integration, PTPd will just serve system time. This feature, once configured, will cause PTPd to disable NTPd when it is syncing the clock, and re-enable it when it isn't. Is this what you are looking for?

**Comment by jllorente** [comment]
Thank you @wowczarek for the explanation. I was under the assumption that PTPd would somewhat trigger regular updates via the ntpd to sync the time, or something. I'm quite new to these time synchronization technologies. Thanks again for the explanation :)
